version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    depends_on:
      - backend